### ISSUE TITLE
Grim doesn't exempt Geyser players on server that run Velocity and NanoLimbo

### ISSUE THREAD

**Issue by noiverre** [GrimAnticheat/Grim#1003]
### Describe the false positive and how to replicate it

1. Install Velocity server
2. Install Geyser and Floodgate
3. Install NanoLimbo server
4. Connect NanoLimbo to backend and Velocity
5. Install floodgate in backend server
6. Login using bedrock client, in this case I use Minecraft for Android

On velocity:
![image](https://user-images.githubusercontent.com/77881970/227424144-8852b3b4-920f-495d-84d1-83d096c36109.png)

On backend, floodgate is installed both in velocity and in backend server:
![image](https://user-images.githubusercontent.com/77881970/227424379-e116a660-e367-4e82-87ae-dab6c81455f2.png)

### Grim version

grimac-2.3.39.jar

### Server version

![image](https://user-images.githubusercontent.com/77881970/227424656-11305e5c-f33b-4eaf-9254-ef175a0b6fc5.png)
![image](https://user-images.githubusercontent.com/77881970/227424685-764e03a6-e285-4c78-9ad9-880ff5d7b65b.png)

### Plugins

![image](https://user-images.githubusercontent.com/77881970/227424753-38294ed9-5895-49e7-ac98-5e9f93aafdc2.png)

**Comment by noiverre** [comment]
Saw other issue related to Bedrock checks, this line doesn't appear in the console

[09:58:02 INFO]: [floodgate] Floodgate player logged in as .Define_Outside joined (UUID: 00000000-0000-0000-0009-01f7ed6f3737)
[09:58:03 INFO]: .Define_Outside joined the game
[09:58:03 INFO]: .Define_Outside[/123.456.789.123:0] logged in with entity id 128 at ([world]-2.5, 101.0, 3.5)
> [09:58:20 INFO]: This player is exempt from all checks!
> [09:58:20 INFO]: User connection state: PLAY

**Comment by MachineBreaker** [comment]
Did you configured correctly Floodgate?

**Comment by noiverre** [comment]
```yaml
remote:
  # The IP address of the remote (Java Edition) server
  # If it is "auto", for standalone version the remote address will be set to 127.0.0.1,
  # for plugin versions, it is recommended to keep this as "auto" so Geyser will automatically configure address, port, and auth-type.
  # Leave as "auto" if floodgate is installed.
  address: auto
  # The port of the remote (Java Edition) server
  # For plugin versions, if address has been set to "auto", the port will also follow the server's listening port.
  port: 25560
  # Authentication type. Can be offline, online, or floodgate (see https://github.com/GeyserMC/Geyser/wiki/Floodgate).
  # For plugin versions, it's recommended to keep the `address` field to "auto" so Floodgate support is automatically configured.
  # If Floodgate is installed and `address:` is set to "auto", then "auth-type: floodgate" will automatically be used.
  auth-type: floodgate
  # Allow for password-based authentication methods through Geyser. Only useful in online mode.
  # If this is false, users must authenticate to Microsoft using a code provided by Geyser on their desktop.
  allow-password-authentication: true
  # Whether to enable PROXY protocol or not while connecting to the server.
  # This is useful only when:
  # 1) Your server supports PROXY protocol (it probably doesn't)
  # 2) You run Velocity or BungeeCord with the option enabled in the proxy's main config.
  # IF YOU DON'T KNOW WHAT THIS IS, DON'T TOUCH IT!
  use-proxy-protocol: false
  # Forward the hostname that the Bedrock client used to connect over to the Java server
  # This is designed to be used for forced hosts on proxies
  forward-hostname: false
```
