### ISSUE TITLE
Forge Mods Placeholder & Join Commands

### ISSUE THREAD

**Issue by ManInMyVan** [GrimAnticheat/Grim#1358]
### Feature description
Forge clients send a list of installed mods when joining a server, however I believe they stopped doing this in modern versions (about 1.17). Configurable join commands could be implemented, which would (as the name implies) executes a command on join (commands should happen in the order they are specified in the config), an example config can be found below (the same could be done for brands). A placeholder could be added for the the player's forge mods, `%mods%` or `%forge_mods%` for example. The format could be as seen below, or `No Forge Mods` if the packet isn't sent.
```yaml
Forge mods (2):
  skinlayers3d 1.2.0
  foamfix 0.6.3a
```
```yaml
# a better name should be used
forge_mod_join_commands:
  # if a player joins with foamfix and 3dskinlayers,
  # they will get kicked for "FoamFix 0.6.3a is not allowed!"
  # then banned for "3dSkinLayers is not allowed!"
  foamfix:
    version: 0.6.3a
    command: kick %player% FoamFix 0.6.3a is not allowed!
  skinlayers3d:
    version: *
    command: ban %player% 3dSkinLayers is not allowed!
```
