### ISSUE TITLE
strange behaviour with item components

### ISSUE THREAD

**Issue by Darwin1546** [GrimAnticheat/Grim#2087]
### Describe the false positive and how to replicate it

Item components:
```
      consumable:
        consume_seconds: float:999999
        animation: string:spyglass
        has_consume_particles: byte:0
```

addition components applied on use:
```
        equippable:
          slot: string:mainhand
          camera_overlay: string:gui/camera
```

https://github.com/user-attachments/assets/1ad9d358-2df9-49bb-b0ee-444cb8bed69a

### Grim version

grimac-2.3.71, grimac-2.3.72dev

### Server version

This server is running Paper version 1.21.4-226-ver

### Client version

1.21.4

### Plugins

AriKeys, Citizens, dDiscordBot, Denizen, Depenizen, GrimAC, LuckPerms, Megizen, ModelEngine, MythicMobs, PlasmoAddon, PlasmoVoice, Vault, ViaVersion, WorldEdit
